### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by balint828** [bartbols/MUSHAR-toolbox#2]
Hi Bart! 

I am Balint again, I think it is better to address my question here if maybe somebody has the same issue :) 
I am just wondering how to generate a similar figure to the
![Uploading overview.png…]()
 provided images. 
Thank you for your help again! 

Best wishes,
Bálint

**Comment by bartbols** [comment]
Hi Bálint

The link to the figure refers back to this issue, so I can't see which figure you mean. Can you include a screenshot or so?

Bart

**Comment by balint828** [comment]
Hello Bart! 

Sorry for the error! I am attaching the figure now. I am interested in the last two sections. I found the mean shape data, but I couldn't figure it out the arrangement of the results. I am also would like to generate a similar plot with the absolute distance and the significance overlayed on the mean shapes. 
Thank you for your help again!

Best wishes,
Bálint

![overview](https://github.com/bartbols/MUSHAR-toolbox/assets/165617785/3e4a194f-e178-4110-9711-6ced8447f762)

**Comment by HEL729242973** [comment]
Hello Bart!
I'm also encountering with this issue to generate a similar plot, could u provide any suggestions? Looking forward to discussing with you. Thanks again for your help.
With regards,
Song Yang

**Comment by HEL729242973** [comment]
> Hello Bart!
> 
> Sorry for the error! I am attaching the figure now. I am interested in the last two sections. I found the mean shape data, but I couldn't figure it out the arrangement of the results. I am also would like to generate a similar plot with the absolute distance and the significance overlayed on the mean shapes. Thank you for your help again!
> 
> Best wishes, Bálint
> 
> ![overview](https://private-user-images.githubusercontent.com/165617785/321611931-3e4a194f-e178-4110-9711-6ced8447f762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzUxNzgsIm5iZiI6MTcxNDk3NDg3OCwicGF0aCI6Ii8xNjU2MTc3ODUvMzIxNjExOTMxLTNlNGExOTRmLWUxNzgtNDExMC05NzExLTZjZWQ4NDQ3Zjc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNTU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGFmY2I2MTZkZmIwNmEyMGEyNmE4MjFmNmM3OTFjOGQ2ODkyZGI4ODhmMWIwMjdiMDM0ZTRlOGE4M2MzYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QjjIJ4VTdoTpEI0COBcF0QMbmierTd-V5Vg-77vwV3w)

Hello Bart!
I'm also encountering with this issue to generate a similar plot, could u provide any suggestions? Looking forward to discussing with you. Thanks again for your help.
With regards,
Song Yang

**Comment by bartbols** [comment]
Sorry for the slow response to this issue. When you run script DEMO_04_compare_shapes.m a plot should show up with four shapes and four distributions of distances. The top left panel is colour-coded by the mean difference between two groups of shapes, while the top right panel is colour-coded by the statistical significance. (Note that the two panels in the middle on the top row show the lower and upper bound of the 95% CI but are not included in the overview figure you copied in above.) You can create composite figures by creatively copy/pasting from these graphs and of course you can customize certain aspects of the plot (for example the range of distances you want to use for colour-coding). I suggest you look in the function bootstrap_surface.m for how to update the plot (from around [here](https://github.com/bartbols/MUSHAR-toolbox/blob/73120660ee394bcf68883d36b9b647859a596fa8/src/bootstrap_surface.m#L213))

**Comment by balint828** [comment]
Hi Bart! 
Thank you very much! No worries for the delay :) 
As you described the results it all makes sense now. Thanks for clarifying it for me. I have a question about the interpretation of the results. If I understand correctly, the DEOM04 does one average shape for both groups, then the difference from this mean shape is presented in the first panel (first-row first plot). In this case, I understand that the difference is from the before training condition. But if I want to compare two groups (independent sample t-test), then the figure should be similar to the one I attached before? Like one showing the difference between the mean shape and group 1 and a second showing the difference between the mean shape and group 2? Or in the example plot  (DEOM04, first row, first plot) the difference representing the difference between the groups regardless of the mean shape? If so how to decide which group has local expansion and local contraction in different areas? I made an attempt and changed line 68 (' 'paired',true,... % set to true if the data are paired - make sure entries in group 1 and group 2 are corresponding') to false. Is this would be enough to run the code for the independent t-test? 

Best wishes,
Bálint

**Comment by bartbols** [comment]
Hi Bálint
The first panel shows the mean difference in shape between group 1 and 2, so it is *not* the difference of group 1 (or 2) relative to the overall mean shape (average of group 1 and 2). The difference is calculated as group 2 minus group 1 (see comment on [line 63](https://github.com/bartbols/MUSHAR-toolbox/blob/73120660ee394bcf68883d36b9b647859a596fa8/DEMO_04_compare_shapes.m#L63) in DEMO_04 as well), so positive values indicate local expansion of the mean shape of group 2 relative to the mean shape of group 1 and conversely, negative values indicate local contraction of the mean shape of group 2 relative to the mean shape of group 1.
If the shapes in the groups are not paired, you should set "paired" to false and the order of the shape indices in variable "group1" and "group2" does not matter. If they are paired (e.g., same subject before and after an intervention), set "paired" to true and make sure that the order of subjects in group 1 and group 2 are matched.
I hope this helps.
Bart

**Comment by balint828** [comment]
Hi Bart! 

Thank you very much! It is clear now :) 

Bálint

**Comment by balint828** [comment]
Hi Bart!

Thank you very much! It is clear now :)

Bálint
