### ISSUE TITLE
Grid Spacing

### ISSUE THREAD

**Issue by JenFerrisPhD** [bartbols/MUSHAR-toolbox#3]
Hi Bart, I've been playing with the B-Spline registration and I was wondering whether [this line](https://github.com/bartbols/MUSHAR-toolbox/blob/b16d7f7aa2a63cdd48ad2fa05281df52e0729c55/parfiles/parameters_BSpline10.txt#L23C34-L23C42) should be 

<(FinalGridSpacingInPhysicalUnits 10 10 10)>

rather than

<(FinalGridSpacingInPhysicalUnits 20 20 20)>

if it's from 10mm grid spacing. I can't see a difference between this file (parameters_BSpline10.txt) and the parameters_BSpline20.txt file and thought this may be it.

Thanks, Jen

**Comment by bartbols** [comment]
Thanks for spotting this Jen! Indeed, it should have been <(FinalGridSpacingInPhysicalUnits 10 10 10)>.
I've updated the file.

**Comment by bartbols** [comment]
parameters_BSpline10.txt updated
